### ISSUE TITLE
Chip asimmetriche nella sezione Notizie

### ISSUE THREAD

**Issue by alranel** [teamdigitale/innovazione.gov.it-site#14]
Le chip utilizzate per gli "argomenti in evidenza" della sezione Notizie sono leggermente asimmetriche:

<img width="413" alt="Screenshot 2021-02-05 at 10 05 16" src="https://user-images.githubusercontent.com/594957/107012721-af155480-6799-11eb-919b-e968847b4419.png">

La soluzione è aggiungere la classe `chip-simple` all'elemento `<a>`

**Comment by Fupete** [comment]
Promemoria da verificare, minor fix: in tutti e quattro i casi d'uso — card in highlight, pre-footer, foglia, esplora argomenti — sostituire nel tag `<a` che contiene le chip le due sole classi `chip mr-3 ...` con queste 5 `chip chip-simple ml-1 mt-1 mr-1 ...`

**Comment by Fupete** [comment]
✅
