### ISSUE TITLE
Subdomain takeover

### ISSUE THREAD

**Issue by pizzolante** [teamdigitale/innovazione.gov.it-site#15]
Ciao, con il commit a2b848e251d92ab1c15eeeaffa3e925338db50e4 è rimasto "scoperto" il sottodominio di pre-produzione.

**Comment by francescozaia** [comment]
Grazie tante @pizzolante.
Ho chiesto di rimuoverlo, entro domani dovremmo riuscire ad avere un feedback.

**Comment by francescozaia** [comment]
Ciao, confermo la cancellazione del sottodominio. Grazie ancora per la segnalazione! 🌈
