### ISSUE TITLE
Accessibilità collegamenti a file PDF

### ISSUE THREAD

**Issue by Fupete** [teamdigitale/innovazione.gov.it-site#34]
**Problema**
Questo `if` [qui](https://github.com/teamdigitale/innovazione.gov.it-site/blob/5905059b0bcbac1a98e61922877d47c30c9ec7ec/lib/text_helpers.rb#L45) ha un errore perché risulta vero `true` anche per i collegamenti a file formato PDF, e non dovrebbe essere così per come progettato.

**Quello che succede**
In pratica i link `<a` inseriti nel corpo del testo a file PDF non ottengono ad esempio l’etichetta " (PDF)" pensata per rispondere alle WCAG, che sarebbe applicata dalle due righe più sotto 47-48 con l’`else if`.

**Possibile soluzione**
È da verificare prima, ma potrebbe bastare invertire `if` e `else if`… controllare prima se è un file PDF e altrimenti...

**Comment by westcoast** [comment]
Fixed, verificabile in Develop
