### ISSUE TITLE
Stato avanzamento CIE

### ISSUE THREAD

**Issue by fiorins** [teamdigitale/innovazione.gov.it-site#46]
Buongiorno, perché dal sito di innovazione.gov.it sono stati tolti i grafici che mostrano gli avanzamenti e i progressi della CIE nei vari comuni ?

**Comment by fiorins** [comment]
Ma risponde qualcuno o è abbandonata la repository ?

**Comment by Fupete** [comment]
Salve Davide @fiorins,

nel nuovo sito web, online dal 4 febbraio, le dashboard del precedente sito web non sono state reintegrate _as-is_ in attesa di verifiche su accessibilità e privacy. 

La dashboard a cui si riferisce è ancora raggiungibile [qui](https://dashboards.innovazione.gov.it/public/dashboard/2cad5098-aa8a-453d-a3da-6a239ccef62c) per ogni eventualità. 

Un saluto.
